# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SignIn_Kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='expires_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='token',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='token',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
