# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignIn_Kiosk', '0002_auto_20160706_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_in',
            field=models.IntegerField(default=0),
        ),
    ]
