# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 22:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SignIn_Kiosk', '0003_auto_20160706_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='expires_timestamp',
        ),
        migrations.AddField(
            model_name='token',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 6, 22, 24, 36, 919447, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='expires_in',
            field=models.DateTimeField(blank=True),
        ),
    ]
