# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 20:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('select_appointment', '0003_auto_20160707_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Arrived', 'Arrived'), ('Cancelled', 'Cancelled'), ('Complete', 'Complete'), ('Confirmed', 'Confirmed'), ('In Session', 'In Session'), ('No Show', 'No Show'), ('Not Confirmed', 'Not Confirmed'), ('Rescheduled', 'Rescheduled'), ('', '')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='employer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='employer_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='employer_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='employer_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='employer_zip_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(choices=[('blank', 'blank'), ('hipanic', 'hipanic'), ('not_hispanic', 'not_hispanic'), ('declined', 'declined')], default='blank', max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='home_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.CharField(choices=[('blank', 'blank'), ('indian', 'indian'), ('asian', 'asian'), ('black', 'black'), ('hawaiian', 'hawaiian'), ('white', 'white'), ('declined', 'declined')], default='blank', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_party_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_party_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_party_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='responsible_party_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 8, 20, 18, 51, 505998, tzinfo=utc)),
        ),
    ]
