# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 20:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('select_appointment', '0004_auto_20160708_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 8, 20, 23, 0, 684876, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
