# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('select_appointment', '0006_auto_20160708_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 8, 20, 24, 51, 897831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Arrived', 'Arrived'), ('Cancelled', 'Cancelled'), ('Complete', 'Complete'), ('Confirmed', 'Confirmed'), ('In Session', 'In Session'), ('No Show', 'No Show'), ('Not Confirmed', 'Not Confirmed'), ('Rescheduled', 'Rescheduled'), ('', '')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(choices=[('blank', 'blank'), ('hipanic', 'hipanic'), ('not_hispanic', 'not_hispanic'), ('declined', 'declined')], default='blank', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(choices=[('blank', 'blank'), ('indian', 'indian'), ('asian', 'asian'), ('black', 'black'), ('hawaiian', 'hawaiian'), ('white', 'white'), ('declined', 'declined')], default='blank', max_length=10, null=True),
        ),
    ]
